language: java
jdk:
  - oraclejdk7
  - openjdk7
notifications:
  email:
    recipients:
      - betfair-cougar-dev@googlegroups.com
    on_success: always
    on_failure: always
before_install:
   - "gem install travis-artifacts"
script: "mvn integration-test -Pintegration-test -B -X > mvn.log"
after_script:
  - "travis-artifacts upload --target-path cougar --path mvn.log"
after_failure: # this will of course run only on failure
  - "bash uploadSurefireReports.sh"
env:
 global:
   - "M2_HOME=`which mvn | sed -e 's/\/bin\/mvn//'`"
   - "WHICH_MVN=`which mvn`"
   - "ARTIFACTS_AWS_REGION=eu-west-1"
   - "ARTIFACTS_S3_BUCKET=betfair.travis-ci"
   - secure: "PMdX+2QqkQPpGbKiMRQDPRQeYNMLAqnXvnGb/EhEWdRF9o7pxten5AllxUAVXkx5b88X5x1wPhd4UZj43/lDoRLIwsnHe7Nstc3kWX4g0xXsKty2s2he40bu4Q7aZvsEfpTjm/KNe5cLVOcBKWP3ovgY4JFUP7qWz9R0Z+ttU5Y="
   - secure: "UIM47HAplfuaXAQLe3R10KpK1wCDtzVTLb2Vu6gp92JTlAxnMDJj7AYt0aN7ETaVF+6ZPac7kELQdufctcSKSD6N93tpOusw5yKmk2yk10t8uhzbXsHkN3scUi/0VSZ7gdHOWaNFVejtKSFOHqHOgN6ll93T0iviMhvl6xj7Y/c="
    
